variables:
  configuration: release

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'custom'
    custom: pack
    arguments: '.\Neo.Compiler.MSIL\Neo.Compiler.MSIL.csproj --version-suffix preview-$(Build.BuildNumber) -c $(configuration) -o $(Build.ArtifactStagingDirectory) --include-symbols'

- task: PublishBuildArtifacts@1
  displayName: 'publish build artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'nuget package'